
services:
  web:
    build: .
    image: thedance/cryptotracker:latest
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  celery:
    image: thedance/cryptotracker:latest
    command: celery -A dcp worker 
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - redis
    env_file:
      - ./.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  celery-beat:
    image: thedance/cryptotracker:latest
    command: celery -A dcp beat --loglevel=info   
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - redis
    env_file:
      - ./.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  redis:
    image: redis:latest
    container_name: redis


#automatic update tool for running Docker containers
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1000 --cleanup --label-enable
    restart: unless-stopped
