# Generated by Django 5.2 on 2025-04-25 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("symbol", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_address", models.CharField(max_length=42, unique=True)),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[("COLD", "Cold"), ("HOT", "Hot"), ("SMART", "Smart")],
                        default="HOT",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptocurrencyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date", models.DateTimeField()),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.cryptocurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=20)),
                ("snapshot_date", models.DateTimeField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.address",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.cryptocurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotETHValidator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_index", models.IntegerField()),
                ("public_key", models.CharField(max_length=128)),
                ("balance", models.DecimalField(decimal_places=5, max_digits=20)),
                ("status", models.CharField(max_length=20)),
                ("activation_epoch", models.CharField()),
                ("rewards", models.DecimalField(decimal_places=5, max_digits=20)),
                ("snapshot_date", models.DateTimeField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.address",
                    ),
                ),
            ],
        ),
    ]
