# Generated by Django 5.2 on 2025-04-24 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("cryptotracker", "0001_initial"),
        ("cryptotracker", "0002_alter_account_user"),
        ("cryptotracker", "0003_alter_account_public_address"),
        ("cryptotracker", "0004_cryptocurrency_snapshotassets_staking_and_more"),
        ("cryptotracker", "0005_snapshotethvalidator_delete_staking_and_more"),
        ("cryptotracker", "0006_alter_snapshotethvalidator_options_and_more"),
        ("cryptotracker", "0007_remove_snapshotethvalidator_rewards_eur"),
        ("cryptotracker", "0008_alter_snapshotethvalidator_options_and_more"),
        (
            "cryptotracker",
            "0009_remove_snapshotethvalidator_unique_validator_per_account_and_cryptocurrency",
        ),
        ("cryptotracker", "0010_alter_snapshotethvalidator_options"),
        ("cryptotracker", "0011_alter_snapshotethvalidator_balance"),
        ("cryptotracker", "0012_alter_snapshotassets_snapshot_date_and_more"),
        ("cryptotracker", "0013_alter_snapshotethvalidator_options"),
        ("cryptotracker", "0014_snapshotdate"),
        ("cryptotracker", "0015_remove_snapshotassets_quantity_eur_and_more"),
        ("cryptotracker", "0016_account_name_account_wallet_type"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_address", models.CharField(max_length=42, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[("COLD", "Cold"), ("HOT", "Hot"), ("SMART", "Smart")],
                        default="HOT",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("symbol", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotETHValidator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_index", models.IntegerField()),
                ("public_key", models.CharField(max_length=128)),
                ("balance", models.DecimalField(decimal_places=5, max_digits=20)),
                ("status", models.CharField(max_length=20)),
                ("activation_epoch", models.CharField()),
                ("rewards", models.DecimalField(decimal_places=5, max_digits=20)),
                ("snapshot_date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.account",
                    ),
                ),
            ],
            options={
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="SnapshotDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=20)),
                ("snapshot_date", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.account",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.cryptocurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptocurrencyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date", models.DateTimeField()),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.cryptocurrency",
                    ),
                ),
            ],
        ),
    ]
