# Generated by Django 5.2 on 2025-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="contract_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
