# Generated by Django 5.2 on 2025-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="public_address",
            field=models.CharField(max_length=42),
        ),
    ]
