# Generated by Django 5.2 on 2025-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="address",
            field=models.CharField(max_length=42),
        ),
    ]
