# Generated by Django 5.2 on 2025-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snapshotdate",
            options={"ordering": ["-date"]},
        ),
    ]
