# Generated by Django 5.1.7 on 2025-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptotracker', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='public_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
