# Generated by Django 5.2 on 2025-09-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryptotracker", "0002_alter_useraddress_public_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.useraddress",
                    ),
                ),
                (
                    "error_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.errortypes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated cryptocurrency if error is crypto-specific",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.cryptocurrency",
                    ),
                ),
                (
                    "error_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_errors",
                        to="cryptotracker.errorlog",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated protocol if error is protocol-specific",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptotracker.protocol",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="cryptotracker.snapshot",
                    ),
                ),
            ],
        ),
    ]
