# Generated by Django 5.2 on 2025-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0002_alter_pool_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poolbalance",
            name="address",
        ),
        migrations.RemoveField(
            model_name="poolrewards",
            name="address",
        ),
    ]
