# Generated by Django 5.2 on 2025-05-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0002_alter_snapshotdate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrencyprice",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cryptotracker.snapshotdate",
            ),
        ),
    ]
