# Generated by Django 5.2 on 2025-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0002_alter_pool_contract_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrencynetwork",
            name="token_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
