# Generated by Django 5.2 on 2025-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0003_alter_cryptocurrencynetwork_token_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="activation_date",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
