# Generated by Django 5.2 on 2025-05-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0003_alter_cryptocurrencyprice_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshotdate",
            name="address",
        ),
    ]
