# Generated by Django 5.2 on 2025-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptotracker", "0004_alter_validator_activation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="activation_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="validator",
            name="validator_index",
            field=models.IntegerField(unique=True),
        ),
    ]
